### ISSUE TITLE
serializeToJson turns empty array into null

### ISSUE THREAD

**Issue by zhaopuming** [libmir/mir-ion#101]
For example:

```d
struct Data {
    int[] a;
}

void main() {
    Data da;
    da.a = [];
    writeln("json:", da.serializeToJson);
}
```

outputs:

```json:{"a":null}```

Is `json:{"a":[]}` more appropriate?

**Comment by 9il** [comment]
> Is json:{"a":[]} more appropriate?

null is faster for most JSON representations. An optional attribute can be added to use `[]` instead.

**Comment by 9il** [comment]
An empty non-null array will be serialised as `[]`.

One may want to use ion format because it has `null.list`. Or `@serdeIgnoreOutIf!"a.length == 0"` attribute to ignore output of an empty array.

```
/// Null vs Empty array serialization
unittest
{
    int[] ar;
    assert(ar.serializeJson == "null");

    int[1] ar2;
    assert(ar2[0 .. 0].serializeJson == "[]");
}
```
