### ISSUE TITLE
Key length limited to 255 chars

### ISSUE THREAD

**Issue by charlesgregory** [libmir/mir-ion#140]
I assume this is a known issue, but I didn't see it documented anywhere.
```
import std.stdio;
    string really_long_key = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    AsdfNode root = AsdfNode("{}".parseJson);
    root[really_long_key] = AsdfNode(serializeToAsdf([1]));
    writeln(cast(Asdf) root);
```
This key is 256 characters and throws an exception at the ```writeln``` statement.
```
asdf.asdf.InvalidAsdfException@/home/cgregory/.dub/packages/asdf-0.5.3/asdf/source/asdf/asdf.d(506): ASDF values is invalid for kind = 65
```

**Comment by 9il** [comment]
Yes, according to the spec the key length is `uint8`.
We plan a full rework of ASDF, this issue may be addressed, thought. 
https://github.com/libmir/asdf/blob/master/SPECIFICATION.md

**Comment by 9il** [comment]
The project `mir-ion` that uses Ion binary format for DOM doesn't have this constraint anymore.
