### ISSUE TITLE
Timestamp binary serialization breaks spec

### ISSUE THREAD

**Issue by hatf0** [libmir/mir-ion#144]
While this is a relatively minor nitpick, the unit test:
https://github.com/libmir/mir-ion/blob/5e269ee7a24afd56645fc1644de80c6b2fe68474/source/mir/ion/tape.d#L1008-L1010
is incorrect (at least, according to the Ion binary spec examples):
```
68 80 0F D0 81 81 80 80 80       // 2000-01-01T00:00:00Z with no fractional seconds
69 80 0F D0 81 81 80 80 80 80    // The same instant with 0d0 fractional seconds and implicit zero coefficient
6A 80 0F D0 81 81 80 80 80 80 00 // The same instant with 0d0 fractional seconds and explicit zero coefficient
69 80 0F D0 81 81 80 80 80 C0    // The same instant with 0d-0 fractional seconds
69 80 0F D0 81 81 80 80 80 81    // The same instant with 0d1 fractional seconds
```
It should be (since the coefficient is explicitly stated within the object constructor):
```d
 result = [0x6A, 0x80, 0x0F, 0xD0, 0x87, 0x88, 0x82, 0x83, 0x84, 0xC2, 0x00]; 
 ts = IonTimestamp(2000, 7, 8, 2, 3, 4, -2, 0); 
 assert(data[0 .. ionPut(data.ptr, ts)] == result); 
```

However, it is also in the docs that a parser should automatically default to a zero coefficient (if it is not explicitly defined), but it *may* be better to distinguish between an explicit precision vs an implied precision.

**Comment by 9il** [comment]
The test has _explicit_ precision and the _implicit_ zero coefficient in the same time. It corresponds to the spec.

**Comment by hatf0** [comment]
Hm, I would’ve thought that since it is explicitly stated in the object initializer that it would be an explicit zero coefficient.
