### ISSUE TITLE
Consider starting automated testing with the 'ion-tests' repo

### ISSUE THREAD

**Issue by hatf0** [libmir/mir-ion#149]
Hi! I see that the library has the deserialization facilities in order. 
To ensure compliance with the Ion spec, I'd like to suggest that this project pulls in the [ion-tests](https://github.com/amzn/ion-tests) repo. It requires writing corresponding 

I can help with the leg-work here, and writing the unittests to ensure it's compliant -- I'd love to extend on this library and write a full [PartiQL](https://partiql.org/)-based database engine (eventually). Let me know where I can help, or if it should be put off for later.

**Comment by 9il** [comment]
Hi @hatf0, that is definitely should be added!

Currently, mir-ion doesn't support all binary ion features (symbol tables support is limited).
There is also significant rework in #147, please target this branch until it is merged.
mir-ion is more complex than other Ion implementations because it targets HPC and eventually it should parse JSON to binary Ion as fast as [simdjson](https://github.com/simdjson/simdjson). Text ion isn't implemented yet.

Your help is very welcome. Would you mind writing Ion text lexer (it can use GC if needed)? Then we would be able to connect it to the Ion serializer and parse Ion text.

**Comment by hatf0** [comment]
I'm trying to think of a good way to approach this lexer -- approaching it in the way that `ion-go`/`ion-java` wouldn't be the most optimal for performance, and seems to be completely incompatible with this library's design. As such, I'm thinking of duplicating the JSON SIMD implementation and tweaking it here and there (obviously we would have to add some changes for clobs/blobs/etc). Does that sound good? We could just have it emit the binary representation onto the tape (similar to what the JSON implem does), making it simpler.

**Comment by 9il** [comment]
> I'm trying to think of a good way to approach this lexer -- approaching it in the way that `ion-go`/`ion-java` wouldn't be the most optimal for performance

That is doesn't really matter. For the best performance, one may use binary ion or json instead.



> As such, I'm thinking of duplicating the JSON SIMD implementation and tweaking it here and there (obviously we would have to add some changes for clobs/blobs/etc). Does that sound good?

JSON simd parser is very complex, and it is almost impossible to extend it to Ion. I would highly recommend using a classic lexer approach like in other ion libraries.

> We could just have it emit the binary representation onto the tape (similar to what the JSON implem does), making it simpler.

That is the next step in my mind. Ion text Lexer + binary ion serializer = Ion text parser. I am working on binary ion serializer. So you don't need to care about binary part of Ion logic (except for initial release).

**Comment by hatf0** [comment]
> That is doesn't really matter. For the best performance, one may use binary ion or json instead.

Ah, okay. That helps for how I should design this -- thank you!

> JSON simd parser is very complex, and it is almost impossible to extend it to Ion. I would highly recommend using a classic lexer approach like in other ion libraries.

I noticed, haha. Is there any way you could document the code later on? I'd love to understand what's going on there.

> That is the next step in my mind. Ion text Lexer + binary ion serializer = Ion text parser. I am working on binary ion serializer. So you don't need to care about binary part of Ion logic (at least for initial release). 

Wonderful. I'll get started on it and pull in the ion-tests in my separate branch.

**Comment by hatf0** [comment]
I'll be taking a stab at this -- I have some recently acquired free time. From preliminary testing, though, it looks like we pass a **significant** number of the test cases!!! This is awesome!

**Comment by hatf0** [comment]
@9il I've run into a little snag here -- one of the test-cases, `good/typecodes/T6-large.10n` has this timestamp:
```0097-01-01T00:28:01.000000000000000000019868821885458-00:33```

The current Ion Timestamp code fails with an "illegal timestamp" exception as it can only parse a fraction coefficient up to 12 digits large, and this coefficient is 14 digits. I think for the sake of compatibility that we shouldn't error here -- it looks like all other Ion implementations don't, and round / truncate the value.

**Comment by 9il** [comment]
The current `Timestamp` size is 16 bytes. Supporting correct parsing of 34 digit fraction will require 32 bytes struct and additional code complexity. This is an undesired thing.

Rounding/truncation is dangerous for timestamps. I see two possible reasons why this kind of timestamp can appear. One is a bad source (human error or code with silly double formatting), then it is probably worth throwing an exception. Another one is correct scientific or high-frequency sensor information, for both the exact value can be critical, and silently rounding it can be a really bad idea.

**Comment by 9il** [comment]
I would rather add a note with the implementation limitations.

**Comment by hatf0** [comment]
> 
> 
> The current `Timestamp` size is 16 bytes. Supporting correct parsing of 34 digit fraction will require 32 bytes struct and additional code complexity. This is an undesired thing.

I agree. 

> Rounding/truncation is dangerous for timestamps. I see two possible reasons why this kind of timestamp can appear. One is a bad source (human error or code with silly double formatting), then it is probably worth throwing an exception. Another one is correct scientific or high-frequency sensor information, for both the exact value can be critical, and silently rounding it can be a really bad idea.

Fair enough. I'll skip this test case.

**Comment by hatf0** [comment]
Starting on getting this in today and attaching it to CI
