### ISSUE TITLE
lexer update

### ISSUE THREAD

**Issue by 9il** [libmir/mir-ion#153]
1. Code should be less generic or almost nongeneric.  Support only `const(char)[]` input and only UTF-8 format. This will speed up compilation speed for huge projects a lot. Code flexibility is less important here. Also, this will allow making code much  CPU cache-friendly. It would be faster to convert other UTF formats to UTF-8 and then parse it.
2. Next level lexer or proto parser is required. Maybe some API of an input range of lexemes such as `structBegin, structEnd, listBegin, listEnd, arrayBegin, arrayEnd, `:`, string, number (`const(char)[]`), timestamp (`const(char)[]`), `const(char)[]` (already prepared string)`. The strings, if they have the representation in the input that corresponds to unescaped sting, then just a slice of the input should be returned.
3. Do we need the whole `std.range`?  Can we have selective import from `std.range.primitives` instead?
4. unit_threaded should be removed. We don't want to depend on it even for testing purposes.

**Comment by hatf0** [comment]
1. Sounds good to me. I just didn’t want to take any assumptions and use only char/wchar/dchar, but I’m completely open to migrating all of it back over to just using char/const(char)[]. Should simplify a lot (and remove the overhead from having nearly every function be a template). 

2. I completely agree -- I was planning on building out that functionality in a later PR, this was just meant to get a basic lexer off of the ground. I’ll get a new PR up and ready for that by around tomorrow so we can have a more developer-friendly API.

3. I believe all we need is primitives - I’ll make the imports more specific.

4. Sounds good — I was experiencing some weird quirks depending on it, and I’m okay with ditching it. Is it alright to depend on `std.exception` here for assertThrown/assertNotThrown?

**Comment by 9il** [comment]
> 4\. Sounds good — I was experiencing some weird quirks depending on it, and I’m okay with ditching it. Is it alright to depend on `std.exception` here for assertThrown/assertNotThrown?

Yes, please use import inside the unittest block. Sometimes `version(unittest)` doesn't work as expected.

**Comment by hatf0** [comment]
I believe this is fixed with the merge of #158
