### ISSUE TITLE
Loop skeleton for Ion parser

### ISSUE THREAD

**Issue by 9il** [libmir/mir-ion#174]
@hatf0 Could you please write a parser loop skeleton for Ion parser? I will add then `ionPut*` primitives from the `tape.d`. I am sorry for bothering with stuff I promised to do myself.

**Comment by hatf0** [comment]
Sure! I'll take a look here over the weekend.

**Comment by hatf0** [comment]
Turns out the weekend means a month or so. My bad!

I'll take a look at this again.
