### ISSUE TITLE
@nogc deserializeText

### ISSUE THREAD

**Issue by 9il** [libmir/mir-ion#190]
It is a priority issue. Also, it doesn't make sense to have `deserializeText` that accept extern symbol table. At least, the current  implementation aren't correct so please remove them. The same for `bool addSymbolTable = true` parameter, it isn't implemented well and doesn't really make sense to support it. Ion text shall add symbol table for new symbols even if the extern symbol table is provided.

**Comment by hatf0** [comment]
Understood — I’ll fix the unit-tests in the mir.ion.deser.text module to use the fixed API.

Also, re: @nogc deserializeText, I was planning on having it @nogc before merge, but I believe there were a few issues with this (off the top of my head), like:
* mir.ion.ser.ion.putSymbol is not @nogc
* std.base64 is not @nogc (required for blobs, would like to have this integrated into Mir)
and some others that I don’t remember off the top of my head. They’re not “critical” issues, but they’re blocking deserializeText from going full @nogc.

**Comment by 9il** [comment]
> Understood — should I fix the unit-tests in the mir.ion.deser.text module to use the fixed API?

Yes please. I have comment them for now.

> mir.ion.ser.ion.putSymbol is not @nogc

It can be nogc. 

```
struct IonSerializer(TapeHolder, string[] compiletimeSymbolTable, bool tableGC = true)
```

Change the last param to `false`.

> std.base64 is not @nogc (required for blobs, would like to have this integrated into Mir)

Disable Clob support for now.

**Comment by hatf0** [comment]
> It can be nogc.
> 
> ```
> struct IonSerializer(TapeHolder, string[] compiletimeSymbolTable, bool tableGC = true)
> ```
> 
> Change the last param to `false`.

I was wondering what that parameter does! Understood — I’ll get that in ASAP.
> > std.base64 is not @nogc (required for blobs, would like to have this integrated into Mir)
> 
> Disable Clob support for now.

I think I can just disable the blob handling portion for now, as I believe regular clobs are fine.

**Comment by hatf0** [comment]
I'm running into an issue with this, which I'm not easily able to figure out the root of.

In `IonTextDeserializer.registerHandlers()`, we do these work-arounds:
https://github.com/libmir/mir-ion/blob/023e52b48501f1ed9569f728ab8a24b3f2eb510e/source/mir/ion/deser/text/package.d#L174-L182
and
https://github.com/libmir/mir-ion/blob/023e52b48501f1ed9569f728ab8a24b3f2eb510e/source/mir/ion/deser/text/package.d#L201-L204


These allocate closures over `this` (IonTextDeserializer) for some unknown reason, which results in this error when we turn on @nogc:
```
Error: constructor `mir.ion.deser.text.IonTextDeserializer!(IonSerializer!(IonTapeHolder!32768LU, null, false), false).IonTextDeserializer.this` is `@nogc` yet allocates closures with the GC
```

The obvious solution is to do
```d
typeHandlers[entry.type] = &member;
```
but that results in
```
Error: address of variable `this` assigned to `this` with longer lifetime
```

I've tried addressing this by:
* merging the registerHandlers function body with the constructor
* passing the `IonTokenizer` object to each handler manually
* generally re-arranging functions

but I *really* cannot figure out what is going on here. @9il please advise

**Comment by 9il** [comment]
The handlers are useless here. Simply get rid of them. A method that accept a enum and does switch is a replacement.

**Comment by hatf0** [comment]
I've taken your replacement and implemented it. The second issue lies here:
https://github.com/libmir/mir-ion/blob/023e52b48501f1ed9569f728ab8a24b3f2eb510e/source/mir/ion/conv.d#L219-L227

I imagine the only solution here would be to return a ScopedBuffer or manual memory management, but I could be entirely wrong.

**Comment by 9il** [comment]
The current GC based API should be preserved.

In the same time it worse to add another one API that accepts a user-provided output buffer. `deserializeText` and  GC based API of `text2ion` and  should create `auto appender = scopedBuffer!ubyte;` and send it to a @nogc version of `text2ion`. Then the result of `appender.data` can be used with `deserializeIon` and `idup` retrospectively. 

BTW, your code sample has a space optimisation bug. Because of compiletime keys are null the compiletime table is empty. So, `ctPrefixAndTable` should be replaced with `ionPrefix`.

**Comment by 9il** [comment]
Also, `IonSymbolTable` should be used in a @nogc version.
```
    IonSymbolTable!false table = void;
    table.initialize;
```

For `IonSymbolTable` you can a trustred  a wrapper similar to `scopedBuffer`. This will help for safety propagation. 
```
auto scopedBuffer(T, size_t bytes = 4096)() @trusted
{
    ScopedBuffer!(T, bytes) buffer = void;
    buffer.initialize;
    return buffer;
}
```

**Comment by 9il** [comment]
Ah, text2ion GC and noGC version should have distinct implementation because the first one should be CTFE-able (please open an issue for that). Thus, GC version should use `IonSymbolTable!true` while nogc version should use `IonSymbolTable!false`.

**Comment by hatf0** [comment]
OK. I've kept the GC-based API, and added a new one with a `out ScopedBuffer!(ubyte)` parameter which is @nogc.

However, when implementing the @nogc `deserializeText`, apparently `deserializeIon` is not @nogc and fails to compile. Am I missing something here?

**Comment by 9il** [comment]
> OK. I've kept the GC-based API, and added a new one with a `out ScopedBuffer!(ubyte)` parameter which is @nogc.

`ref Appender`, where Appender is a template parameter.

> However, when implementing the @nogc `deserializeText`, apparently `deserializeIon` is not @nogc and fails to compile. Am I missing something here?

It maybe GC because not all of the types are @nogc. For example numbers, `RCArray`, and `SmallString` are @nogc types.

**Comment by hatf0** [comment]
Hm. A simple struct like:
```d
struct Book {
    bool wouldRecommend;
}
```
results in:
```d
__traits(compiles, () @nogc { deserializeIon!Book(); }); // returns false
```

I think this is a separate issue -- I have all of the @nogc code implemented, but deserializeIon is just flat-out failing here.

**Comment by 9il** [comment]
> I think this is a separate issue -- I have all of the @nogc code implemented, but deserializeIon is just flat-out failing here.

OK then

**Comment by 9il** [comment]
BTW, the example is wrong. `deserializeIon` missing arguments.

**Comment by 9il** [comment]
`deserializeIon ` is @nogc:

```d
version(mir_ion_test)
@nogc unittest
{
    import mir.serde: serdeIgnoreIn, serdeIgnore, serdeScoped;
    import mir.bignum.decimal;
    import mir.rc.array;
    import mir.small_array;
    import mir.small_string;

    static struct Book
    {
        SmallString!64 title;
        bool wouldRecommend;
        SmallString!128 description; // common `string` and array can be used as well (with GC)
        uint numberOfNovellas;
        Decimal!1 price;
        double weight;

        // nogc small-array tags
        SmallArray!(SmallString!16, 10) smallArrayTags;

        // nogc rc-array tags
        RCArray!(SmallString!16) rcArrayTags;

        // nogc scope array tags
        // when used with `@property` and `@serdeScoped`
        @serdeIgnore bool tagsSet; // control flag for test

        @serdeScoped
        void tags(scope SmallString!16[] tags) @property @safe pure nothrow @nogc
        {
            assert(tags.length == 3);
            assert(tags[0] == "one");
            assert(tags[1] == "two");
            assert(tags[2] == "three");
            tagsSet = true;
        }
    }

    /// FIX ME: see also commented out Book in JSON as an example.
    static immutable ubyte[] data = [0x3, 0x4];
    auto d = data.deserializeIon!Book;
}
```

**Comment by hatf0** [comment]
WTF. After looking at the code again, it seems to work just fine (????)

I think it was the missing argument (as you said) that was causing it to fail, but I have no clue why it works now.
