### ISSUE TITLE
serialization of std.typecons.Typedef segfaults because the recursion loops

### ISSUE THREAD

**Issue by Panke** [libmir/mir-ion#196]
```
alias Id = Typedef!(int, 0, "id");

unittest
{
   Id id = Id(12);
   writeln(serializeJson(id));
}
```

Backtrace shows an infinite recursive loop.

**Comment by 9il** [comment]
We aren't going to support Phobos types. `Typedef` should add `serdeIgnore` to appropriate properties, which wouldn't happen. As a workaround one can use `serdeProxy`: `struct S{ @serdeProxy!int Typedef!(int, 0, "id") field; }`
