### ISSUE TITLE
implementing custom (de)serializer guide

### ISSUE THREAD

**Issue by WebFreak001** [libmir/mir-ion#26]
I think mir-ion is a great base for (de)serializers, as it already includes a few formats I think it would be interesting for users to know how to extend it to add their own ones.

**Comment by 9il** [comment]
For serialization a serialiser structure should be implemented to satisfy the interface wrapper in `mir.ser.interfaces`. The serialiser can throw in case of unexpected types of input data. This user serialization type can be used directly with `mir.ser.serializeValue` function.

The deserialization is done through conversion to binary ion data. 
For example, `handleMsgPackElement` serialise the msgpack input to an ion serialiser. Then `deserializeIon` can be used to deserialise data.
