### ISSUE TITLE
Potential of moving backends out of the project source tree?

### ISSUE THREAD

**Issue by rv32ima** [libmir/mir-ion#3]
Is there any way that we could split out the individual (de)?serialization backends out from the main source tree, and publish them as separate dub packages? Obviously the Ion / Ion Text implementations should remain, but if we're ever planning on adding more backends (i.e. YAML, Protobuf / Cap'n Proto / etc, Flatbuffers), we should definitely see into whether or not we can split these up into their own separate packages. I believe that there is already some work in that regards (with the `ISerializer` interface), but is there any other reason why this hasn't happened yet (other then with the Bloomberg components)?

**Comment by 9il** [comment]
Unlikely something like that may happen.
