### ISSUE TITLE
deserializeJson does not handle associative array arrays properly

### ISSUE THREAD

**Issue by rv32ima** [libmir/mir-ion#6]
Reported by @adamdruppe on the D discord, this fails:
```d
import mir.ion.deser.json : deserializeJson;
string d = `[{"test": 1}, {"second": 2}]`;
writeln(d.deserializeJson!(int[string][])); // prints out [[], []]
```

Upon further investigation, I found that using `deserializeDynamicJson` works here:
```d
writeln(d.deserializeDynamicJson!(int[string][])); // prints out [["test": 1], ["second": 2]]
```

Is this intended behavior? I'm assuming that this is a bug -- please advise @9il.

**Comment by 9il** [comment]
Fixed in the new release.
